name: Anon-SMS Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y git
      
    - name: Clone repository
      run: git clone https://github.com/threatcode/Anon-SMS.git
      
    - name: Navigate to Anon-SMS directory
      run: cd Anon-SMS
      
    - name: Run script
      run: sudo bash Run.sh
